name: Job - Publish

on:
  workflow_call:

jobs:
  publish-jsr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install Dependencies
        run: deno install
      - name: Publish JSR
        run: deno publish

  build-binaries:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install Dependencies
        run: deno install
      - name: Build Binary
        run: |
          deno compile \
            --allow-read \
            --allow-net \
            --allow-env \
            --target ${{ matrix.target }} \
            --output mcp-serve-${{ matrix.target }} \
            main.ts
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcp-serve-${{ matrix.target }}
          path: mcp-serve-${{ matrix.target }}*

  release:
    needs:
      - publish-jsr
      - build-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Publish
        run: |
          gh release create ${{ github.ref }} \
            --generate-notes \
            ./artifacts/*/*
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
