name: On Tag publish

on:
  push:
    tags:
      - "*"

jobs:
  small-test:
    uses: ./.github/workflows/job-test-small.yml
  medium-test:
    uses: ./.github/workflows/job-test-medium.yml
  publish:
    needs:
      - small-test
      - medium-test
    uses: ./.github/workflows/job-publish.yml
    permissions:
      contents: write
      id-token: write
